name: Crawl HJD2048 Data

on:
  workflow_dispatch:
    inputs:
      forum_url:
        description: '论坛 URL (例如，https://hjd2048.com/2048/thread.php?fid=3)'
        required: true
        default: 'https://hjd2048.com/2048/thread.php?fid=3'
      start_page:
        description: '起始页面号 (例如，926)'
        required: true
        default: '926'
      end_page:
        description: '结束页面号 (例如，1)'
        required: true
        default: '1'

permissions:
  contents: write

jobs:
  crawl:
    runs-on: ubuntu-latest
    steps:
      - name: 检出仓库
        uses: actions/checkout@v3

      - name: 设置 Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: 安装依赖
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4 tqdm
          # 如果使用 selenium，取消注释
          # pip install selenium
          # sudo apt-get update
          # sudo apt-get install -y chromium-chromedriver

      - name: 安装 Git LFS
        run: |
          sudo apt-get update
          sudo apt-get install git-lfs
          git lfs install

      - name: 配置 Git
        run: |
          git config --global user.name "pikapk3069"
          git config --global user.email "pikapk3069@outlook.com"

      - name: 提取 fid 和设置 CSV 文件名
        id: extract
        run: |
          FORUM_URL="${{ github.event.inputs.forum_url }}"
          FID=$(echo "$FORUM_URL" | sed -E 's|.*fid=([0-9]+).*$|\1|')
          CSV_FILE="fid_$FID.csv"
          echo "FID=$FID" >> $GITHUB_ENV
          echo "CSV_FILE=$CSV_FILE" >> $GITHUB_ENV
          echo "提取的 FID=$FID, CSV_FILE=$CSV_FILE"

      - name: 运行爬虫
        env:
          FORUM_URL: ${{ github.event.inputs.forum_url }}
          START_PAGE: ${{ github.event.inputs.start_page }}
          END_PAGE: ${{ github.event.inputs.end_page }}
          FID: ${{ env.FID }}
          CSV_FILE: ${{ env.CSV_FILE }}
        run: |
          python crawler.py

      - name: 提交并推送更改
        if: always()
        env:
          CSV_FILE: ${{ env.CSV_FILE }}
        run: |
          git add "$CSV_FILE"
          git commit -m "完成论坛 fid=${{ env.FID }} 的爬取后最终提交" || echo "无更改需要提交"
          git push || echo "推送失败，可能是无更改或权限问题"
